### ISSUE TITLE
Draft Bluesky plan for Citizenship by staff member

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/PresenceChecker#13]
As the business sponsor
I want to see a initial draft of a bluesky approach
For staff members for dealing with citizenship queries

A / C 
 - Should show the experience for the staff member
 - Should consider key current application form requirements
 - Should challenge the existing process
 - Should provide commentary on 'our thinking'

Dependencies:
 - Initial sign off on applicant journey
 - Need to meet with the CSO and see their process

**Comment by karynLabPlus** [comment]
Progress is on hold until we meet with the DIA Citizenship UX team on Tuesday who have been doing work in this area.

**Comment by karynLabPlus** [comment]
3 things we noted to build into wire frames (in some way - potentially as call-outs)

1) Only show minimum information required
2) Record any access to additional information and reason for accessing (log it) - this reason can hopefully be based on context and not require further user input 3)
3) Point out at the fact that it is logged allows for patterns in access to be identified, so that 
  ---- a) departures from proper process  
  ---- b) subjective interpretation 
  ---- c) fraudulent/suspicious activity can be found and acted on.
4) Identify when there are problems matching applicant data across systems .. and communicate how long it is likely to take before the application can continue. 
  ** may need some thought... Kirsty and Yvonne were hoping that we'd communicate how long it was currently taking for INZ to resolve the data match issue... but if you are assuming in your blue-sky view that these issues have all been fixed then might pay to either call this out OR comment about an alternative approach if the data ain't all fixed

**Comment by CharlotteHinton** [comment]
Closing this ticket - as captured in Icebox under #224 so we don't forget.
