### ISSUE TITLE
Source (and receive) demo dataset

### ISSUE THREAD

**Issue by CharlotteHinton** [ServiceInnovationLab/PresenceChecker#2]
25/Oct
We've confirmed we need at least 500 lines for demo data

**Comment by CharlotteHinton** [comment]
Still working to secure demo data - next ETA was 14 November.

**Comment by Br3nda** [comment]
I've written up the structure we are requesting - and Kirtsy has emailed it through to Immigration.

**Comment by Br3nda** [comment]
Current request for data on Citizen Application Presence check is:

```
[Clients]
Client ID, File Number

[Identities]
Client ID, Identity No, Surname, First name, Second name,  Third name, Gender, Country of Birth, Nationality, Issuing State, Serial No.

[Movements]
Identity No, Movement (arrival/departure), Carrier Time/Date

[Visas_and_Permits]
Identity No, Visa or Permit, Type, S/M, Date Issued, Start Date, Visa Expiry Date
```

Note:
We've matched the column names to an existing paper report the Citizenship team receive from immigration - they're not modern identity practice (we wouldn't call someone's names first and last etc today because that's not how names work) but they seem to be what the columns were called at some point when databases were created.

When we create our own column names we need to decide if we following their naming, or move to today's identity standards.

**Comment by robholmesnz** [comment]
Expecting data on 12 December.

**Comment by robholmesnz** [comment]
Data has arrives. Review of data and suitability is separate card.
